export const munichQuestions = {
  general: [
    {
      id: "tum_intake",
      label: "Which semester are you applying for?",
      type: "select",
      required: true,
      options: ["Winter semester", "Summer semester"],
    },
    {
      id: "tum_study_level",
      label: "What level of study are you applying for?",
      type: "select",
      required: true,
      options: ["Bachelor's", "Master's", "PhD"],
    },
    {
      id: "tum_uni_assist_vpd",
      label: "Have you applied for preliminary documentation/VPD through uni-assist?",
      type: "select",
      required: true,
      options: ["Yes", "No", "Not applicable yet"],
    },
    {
      id: "tum_visa_awareness",
      label: "Do you understand that you may need a German student visa/residence permit?",
      type: "select",
      required: true,
      options: ["Yes", "No"],
    },
  ],

  academics: [
    {
      id: "program",
      label: "Select your intended TUM program",
      type: "select",
      required: true,
      options: [
        "Aerospace",
        "Architecture",
        "Automotive Engineering",
        "Biomedical Engineering and Medical Physics",
        "Chemical Biotechnology",
        "Civil Engineering",
        "Computational Mechanics",
        "Computer Science",
        "Data Engineering and Analytics",
        "Electrical Engineering and Information Technology",
        "Environmental Engineering",
        "Food Technology",
        "Games Engineering",
        "Health Science",
        "Industrial Biotechnology",
        "Information Engineering",
        "Management and Technology",
        "Mathematics",
        "Mechanical Engineering",
        "Mechatronics, Robotics and Biomechanical Engineering",
        "Physics",
        "Politics and Technology",
        "Power Engineering",
        "Quantum Science and Technology",
        "Robotics, Cognition, Intelligence",
        "Sustainable Management and Technology",
        "Technology of Biogenic Resources",
      ],
    },
    {
      id: "tum_entrance_qualification",
      label: "What qualification are you applying with?",
      type: "select",
      required: true,
      options: [
        "KCSE",
        "A-Levels",
        "International Baccalaureate",
        "German Abitur",
        "American High School Diploma",
        "Other international qualification",
      ],
    },
    {
      id: "tum_relevant_subjects",
      label: "List your strongest relevant subjects for this program",
      type: "textarea",
      required: true,
      placeholder:
        "Example: Mathematics, Physics, Chemistry, Computer Studies, Biology.",
    },
    {
      id: "tum_previous_university_study",
      label: "Have you completed any previous university study?",
      type: "select",
      required: true,
      options: ["Yes", "No"],
    },
  ],

  testing: [
    {
      id: "tum_language_track",
      label: "What is the main teaching language of your intended program?",
      type: "select",
      required: true,
      options: ["German", "English", "Both German and English", "Not sure"],
    },
    {
      id: "tum_german_proof",
      label: "Do you have German language proof?",
      type: "select",
      required: true,
      options: [
        "TestDaF",
        "DSH",
        "Goethe Certificate",
        "telc Deutsch",
        "No German proof yet",
        "Not required for my program",
      ],
    },
    {
      id: "tum_english_proof",
      label: "Do you have English language proof?",
      type: "select",
      required: true,
      options: [
        "IELTS",
        "TOEFL",
        "Cambridge English",
        "PTE Academic",
        "No English proof yet",
        "Not required for my program",
      ],
    },
    {
      id: "tum_language_score",
      label: "Enter your language test score if available",
      type: "text",
      required: false,
      placeholder: "Example: IELTS 7.0, TOEFL 100, TestDaF TDN 4",
    },
  ],

  activities: [
    {
      id: "tum_technical_projects",
      label: "Describe any technical, research, coding, engineering, or science projects you have completed",
      type: "textarea",
      required: false,
      placeholder:
        "Mention project title, tools used, your role, and impact.",
    },
    {
      id: "tum_internship_experience",
      label: "Do you have internship, lab, industry, or practical experience related to your program?",
      type: "textarea",
      required: false,
    },
    {
      id: "tum_competitions",
      label: "List any Olympiads, science fairs, hackathons, innovation contests, or academic competitions",
      type: "textarea",
      required: false,
    },
  ],

  family: [
    {
      id: "tum_funding_source",
      label: "How do you plan to fund your studies in Germany?",
      type: "select",
      required: true,
      options: [
        "Family support",
        "Scholarship",
        "Personal savings",
        "Sponsor",
        "Education loan",
        "Combination of sources",
      ],
    },
    {
      id: "tum_blocked_account_awareness",
      label: "Are you aware that Germany may require proof of financial resources, such as a blocked account?",
      type: "select",
      required: true,
      options: ["Yes", "No"],
    },
  ],

  documents: [
    {
      id: "tum_school_certificate",
      label: "School leaving certificate / KCSE certificate",
      type: "file",
      required: true,
    },
    {
      id: "tum_transcripts",
      label: "Academic transcripts / result slips",
      type: "file",
      required: true,
    },
    {
      id: "tum_vpd_document",
      label: "uni-assist VPD / preliminary documentation if available",
      type: "file",
      required: false,
    },
    {
      id: "tum_language_certificate",
      label: "Language certificate",
      type: "file",
      required: true,
    },
    {
      id: "tum_cv",
      label: "CV / resume",
      type: "file",
      required: false,
    },
    {
      id: "tum_passport",
      label: "Passport biodata page",
      type: "file",
      required: true,
    },
    {
      id: "tum_motivation_letter",
      label: "Motivation letter if required by your program",
      type: "file",
      required: false,
    },
  ],

  recommendations: [
    {
      id: "tum_recommendation_required",
      label: "Does your selected program require recommendation letters?",
      type: "select",
      required: true,
      options: ["Yes", "No", "Not sure"],
    },
    {
      id: "tum_academic_referee",
      label: "Provide academic referee details if required",
      type: "textarea",
      required: false,
      placeholder:
        "Name, position, institution, email, and relationship to you.",
    },
  ],
};