export const torontoQuestions = {
  general: [
    {
      id: "uoft_intake",
      label: "Which intake are you applying for?",
      type: "select",
      required: true,
      options: ["Fall 2026", "Winter 2027", "Summer 2027"],
    },
    {
      id: "uoft_campus",
      label: "Which University of Toronto campus are you applying to?",
      type: "select",
      required: true,
      options: ["St. George", "Scarborough", "Mississauga"],
    },
    {
      id: "uoft_scholarship_interest",
      label: "Would you like to be considered for scholarships?",
      type: "select",
      required: true,
      options: ["Yes", "No"],
    },
  ],

  academics: [
    {
      id: "program",
      label: "Select your intended course/program",
      type: "select",
      required: true,
      options: [
        "Computer Science",
        "Software Engineering",
        "Data Science",
        "Artificial Intelligence",
        "Cybersecurity",
        "Information Technology",
        "Mechanical Engineering",
        "Civil Engineering",
        "Electrical Engineering",
        "Chemical Engineering",
        "Biomedical Engineering",
        "Architecture",
        "Mathematics",
        "Statistics",
        "Physics",
        "Chemistry",
        "Biochemistry",
        "Biology",
        "Environmental Science",
        "Medicine",
        "Nursing",
        "Pharmacy",
        "Dentistry",
        "Public Health",
        "Psychology",
        "Economics",
        "Finance",
        "Accounting",
        "Business Administration",
        "Marketing",
        "International Business",
        "Political Science",
        "International Relations",
        "Law",
        "Criminology",
        "Sociology",
        "History",
        "Philosophy",
        "English Literature",
        "Linguistics",
        "Education",
        "Journalism",
        "Media Studies",
        "Music",
        "Fine Arts",
        "Urban Planning",
      ],
    },
    {
      id: "academic_awards",
      label: "List any academic awards or distinctions",
      type: "textarea",
      required: false,
    },
  ],

  testing: [
    {
      id: "english_test",
      label: "Which English proficiency test did you take?",
      type: "select",
      required: true,
      options: ["IELTS", "TOEFL", "Duolingo English Test", "PTE Academic", "None"],
    },
    {
      id: "english_score",
      label: "Enter your English test score",
      type: "text",
      required: false,
    },
  ],

  activities: [
    {
      id: "extracurriculars",
      label: "List your strongest extracurricular activities",
      type: "textarea",
      required: true,
    },
    {
      id: "leadership",
      label: "Describe any leadership positions held",
      type: "textarea",
      required: false,
    },
  ],

  family: [
    {
      id: "financial_support",
      label: "Who will financially support your studies?",
      type: "select",
      required: true,
      options: ["Parents", "Guardian", "Sponsor", "Scholarship", "Self-sponsored"],
    },
  ],

  documents: [
    {
      id: "passport_document",
      label: "Passport or National ID",
      type: "file",
      required: true,
    },
    {
      id: "academic_transcript",
      label: "Academic transcript",
      type: "file",
      required: true,
    },
    {
      id: "personal_statement",
      label: "Personal statement",
      type: "file",
      required: true,
    },
  ],

  recommendations: [
    {
      id: "recommender_count",
      label: "How many recommendation letters will you submit?",
      type: "select",
      required: true,
      options: ["1", "2", "3"],
    },
    {
      id: "teacher_reference",
      label: "Provide teacher/counselor recommendation details",
      type: "textarea",
      required: true,
    },
  ],
};